name: MacOS Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      BUILD_TYPE: Release
      SDL2_VERSION: 2.0.20

    steps:
    - uses: actions/checkout@v2

    - name: "Install SDL2.0"
      run: brew install SDL2

    - name: "Build Client app"
      run: |
        cmake -S Client -B ${{github.workspace}}/Client/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
        cmake --build ${{github.workspace}}/Client/build

    - name: "Build Server app"
      run: |
        cmake -S Server -B ${{github.workspace}}/Server/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/Server/build

    - name: "Upload build as Artifact"
      uses: actions/upload-artifact@v2.3.1
      if: success()
      with:
        name: checkers-online-macos-${{github.sha}}
        path: |
          ${{github.workspace}}/Client/build
          ${{github.workspace}}/Server/build